#!/bin/bash
#
# Installation script to create symbolic links for all shell scripts inside /usr/local/bin directory,
# so that user can access them globally from anywhere.
#
# Copyright (c) 2015 Matthew Komarnicki
# All rights reserved.
# http://komarnicki.pl

function danger {
	if [ $# = 1 ]; then
		tput setaf 1
		tput bold
		echo $1
		tput sgr 0
	fi
}

scripts=(
    "pack"
    "unpack"
)

c=${#scripts[@]}
s=0
f=0

src=`pwd`
dest="/usr/local/bin"

for script in "${scripts[@]}"
do
    cmd_str="sudo ln -sf $src/$script $dest/$script"
    eval $cmd_str

    if [ $? -eq 0 ]; then
        (( s++ ))
        echo "Installing $script - done"
    else
        (( f++ ))
        danger "Installing $script - unable to create a symlink for the $script script. File does not exist in $src."
    fi
done

echo -e "\n$s Installed"
if [ "$f" -gt 0 ]; then
    danger "$f Failed"
fi
