#!/bin/bash
# GitHub SSH key generation
# https://help.github.com/articles/generating-ssh-keys/

cd ~

if [ -d ".ssh" ]; then

    echo "It looks like .ssh directory already exists."
    read -p "Do you want to remove whole directory and generate new keys?" -n 1 -r

    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        echo -e "\nAborted"
        exit 1
    fi

    rm -rf .ssh
    echo -e "\nOld .ssh directory removed."

fi

echo "Provide GitHub email address"

read EMAIL

if [ "_" = "_$EMAIL" ];
then
    echo "Nothing given!"
    exit 1
elif [[ $EMAIL != *@* ]];
then
    echo "Given e-mail looks like invalid!"
    exit 1
fi

echo "Generating SSH keys. Follow instructions on the screen"

ssh-keygen -t rsa -b 4096 -C "$EMAIL"

echo "Adding SSH key to the ssh-agent"

ssh-add ~/.ssh/id_rsa

echo "Copying SSH key to your clipboard"

pbcopy < ~/.ssh/id_rsa.pub

echo "All good! Your public key has been copied to clipboard. Go to https://github.com/settings/ssh, add new key and paste the content."
