#!/bin/bash
#
# Script to extract tar.bz2 archive into given destination.
#
# Copyright (c) 2015 Matthew Komarnicki
# All rights reserved.
# http://komarnicki.pl

function danger {
	if [ $# = 1 ]; then
		tput setaf 1
		tput bold
		echo $1
		tput sgr 0
	fi
}

if [ $# -ne 2 ]; then
	danger "Invalid usage, try:"
	echo "$0 {source_file} {destination_dir}"
	exit
fi

mkdir -p $2 && tar zxf $1 -C $2
echo -e "\nExtracted! Done!"
