#!/bin/bash
#
# Script to create new packed and compressed tar.bz2 archive.
#
# Copyright (c) 2015 Matthew Komarnicki
# All rights reserved.
# http://komarnicki.pl

function danger {
	if [ $# = 1 ]; then
		tput setaf 1
		tput bold
		echo $1
		tput sgr 0
	fi
}

if [ $# -ne 2 ]; then
	danger "Invalid usage, try:"
	echo "$0 {destination_file} {source_dir}"
	exit
fi

ts=`date '+%F_%T' | sed -e 's/:/_/g'`

tar -cjf $1_${ts}.tar.bz2 $2
echo -e "\nPacked and compressed! Done!"
